baseURL = "https://www.unifica.ai/home"
title = "Unifica"
author = "Kyle S Passarelli"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Unifica"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Unifica"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Herramientas de IA a la medida de la necesidad del cliente, de la mano de nuestros expertos"
    meta_og_title = "Unifica"
    meta_og_type = "website"
    meta_og_url = "https://unifica.ai"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Unifica permite a los tomadores de decisiones de alto nivel iterar rápidamente su estrategia de IA"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@unifica"
    meta_twitter_creator = "@unifica"

[menu]

  # [[menu.main]]
  #   identifier = "products"
  #   name = "Products"
  #   url = "/products/"
  #   weight = 1

  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "/blog/"
  #   weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/unifica-ai"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
